fast_checkout: &fast_checkout
  run:
    name: Checkout zip
    command:  |
      cd ~ && rm -rf project
      curl -s#L https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/archive/$CIRCLE_SHA1.zip | bsdtar -xvf- > /dev/null
      mv $CIRCLE_PROJECT_REPONAME-$CIRCLE_SHA1 project

version: 2
jobs:
  build_and_test:
    macos:
      xcode: "10.1.0"
    steps:
      - <<: *fast_checkout
      - restore_cache:
          keys:
            - wordpress-ios-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "Podfile.lock" }}
            - wordpress-ios-dependencies-{{ checksum "Gemfile.lock" }}
            - wordpress-ios-dependencies-
      - run:
          name: Bundle install
          command: bundle install --path=vendor/bundle
      - run:
          name: CocoaPods Check
          command: (bundle exec pod check && touch .skip_pod_install) || echo "Pods will be updated"
      - run:
          name: Fetch CocoaPods Specs (if needed)
          command: test -e .skip_pod_install || curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Pod Install (if needed)
          command: test -e .skip_pod_install || bundle exec pod install
          environment:
            COCOAPODS_DISABLE_STATS: true
      - save_cache:
          key: wordpress-ios-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "Podfile.lock" }}
          paths:
            - Pods/
            - vendor/bundle
      - run:
          name: Build
          command: xcodebuild -scheme "WordPress" -configuration "Debug" -workspace "WordPress.xcworkspace" -sdk iphonesimulator build-for-testing | bundle exec xcpretty
      - run:
          name: Test
          command: xcodebuild -scheme "WordPress" -configuration "Debug" -workspace "WordPress.xcworkspace" -destination 'platform=iOS Simulator,name=iPhone XS,OS=latest' test-without-building | bundle exec xcpretty -r junit
      - store_test_results:
          path: build/reports

  danger:
    macos:
      xcode: "10.1.0"
    steps:
      - <<: *fast_checkout
      - restore_cache:
          keys:
            - wordpress-ios-danger-{{ checksum "Rakefile" }}-{{ checksum "Gemfile.lock" }}
            - wordpress-ios-danger-{{ checksum "Gemfile.lock" }}
            - wordpress-ios-danger-
      - run:
          name: Dependencies for danger
          command: rake dependencies:bundle:check dependencies:lint:check
      - save_cache:
          key: wordpress-ios-danger-{{ checksum "Rakefile" }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/
      - run:
          name: Danger
          command: bundle exec danger --fail-on-errors=true

workflows:
  version: 2
  wordpress_ios:
    jobs:
      - danger
      - build_and_test
